# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Rl/O+GZx6Ss2UDzIjPT/VJ0SYvezRED+Pv4hby4=,iv:gj3Ga3uTq8wexqQEmTXzs+SVf9pnvrdhufHWFfCztZs=,tag:p1kwpTtrdPEtOZdxG1aNIA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:M1u3eQzQ2L1AxL1m42IQHIP1z0MHCXdW11RtK40A93x6a1TQGA==,iv:yFM1N2s6asV7GgdWISNLp2+TWWU4wM9kV4r6Kr1ig7s=,tag:51TcUaq0JD75MQHpmXNyqg==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:uhMQYTOPmz9P6xwgxl3YPQehs0vtpoVExV1lYdvOitQ=,iv:tWZVROUbjwcnkZOBUjN63a3j/OZAYNV5qwK+9iWRRVc=,tag:7cPi+OUNMZ+zo0OvPQIPpw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:5c7r0Q==,iv:avM0II1lSz+hIlC9peeySPAdzktxy+yXwGEu6AoU3mI=,tag:QDuh7bPg+P0Est9eLQAdUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-24T07:21:06Z"
    mac: ENC[AES256_GCM,data:eKyMP099xI98ZYg/a0M008SJRFWEVMpYTgBxx3lilnwZ+wm+MdZBvtg38rjtwldcOQO8UI/FLFdV94iBYM4iqaoZ8VUSEqowsEVA8GYgmINv3JizSg2n/mHOm1n6IWb7z1aoxsliYLqLcyWSmS3eX3fWY7K81ojXAH8CPeILNFM=,iv:dUDvBNDsExLYQFsUn7Q0F0TdWy5hOPz9JFs6XJdHZok=,tag:XqaemjBV8tegvL8MR4u8Zg==,type:str]
    pgp:
        - created_at: "2021-09-24T07:21:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+Rt2onsqezRARAAt1b/5YOF/NiybpF/TCkrOaa6YAK0lEjam3411DrbaE0m
            9DxxSejoeyqgUjhBkubRmyDGbH5YYSGq8nUeHqMpPBkCyRvppiqmZWyBnvwOOnNQ
            +FN5Icb8IGbmjgGvl5pGms4Y9XfxXOKIvH3oQdJ1/UR517PcisosvSoSv6fZfusT
            WOpP51ewD7Yk4MZ2g3jYMNTQyQTBUz4R01EY8LhL161+N+WAv5KtbXsuZ87vUmwD
            BXDXn9SDG9wiBNJmkLbdnAxWjRE3ndtnx+i9xrvQ2pvjH2SHtqAvegNp6nbMuQJd
            SKpH3fHn7KvN+DH3cp70LKjd51uEf1M+KlJIW4U9cLydvHMhD2Ri+7bR/otW/SFm
            0PhFvXe6ShRJlB8t3OhFb3NSWPl7PhpRHFYXPp1xmiYHETlWjJhx+wfe7JMDuzJO
            rDn8PqVGP7grarzn0IvQVDQxcpJ/i71SPe7f91CR1hBSO4gT/xr+1RPVI8uyc4WQ
            7haFhsFjPgsTy5YYCM/m5PgRFk1CL4QonSzgUyq6XxSousbK556GpcmDNOf/00wq
            SX2/g859PF8hS4zQOECD0/XQMNTLg4Xt5bDTk4h6K7DhKUy1Bs8YsXiECnD3E5qt
            4+m9coNu9KdZkByOaKcsIXW7o48NTF3+QxH0ae+aNUiJ6WQvtqr174ixLWira+DS
            XAE1IIEhdYYAw8LcEEJlicrYD7bEcgdvgWXSuyzo1U1ssK9C0jL8yMYuJCgTx/Np
            sHXpRAGjPFayTahcsIDDeG39u2HtZ/PtiyMj127MrWy6mZwB/ti4BuMpLjIJ
            =a0br
            -----END PGP MESSAGE-----
          fp: EE28A8EBC835173892520CC88C929A715870568E
        - created_at: "2021-09-24T07:21:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6HOrcCh3eSZARAAhKRLJocXRIakXn9Ddaf0UEyh1Evml2QHi4O7QRTrSEh5
            +gRs33ondt9kE7wCjVdSB+IaO05vDdgYYfp2SDKXJSA/RCX7j9gfvvBL1EWTi+81
            b+5g98x28DF0oTnvRJ2WC5p07RvF7rmX/OCPbIg+XtcsXpjmi/3TMCP9UL0UjYRu
            zroAuNT6zbILPxg6/w2tyfUIVWqFz2qsGjRUoKPrEfuiGlunrr0YvCM2YNVN2Xv8
            RcfYaref6jtHFmedUI8MwZxIZ1ZgUqPlmk25dgfn+DvjOb1r3uSva9GV8rfG9tuv
            nLJqVJHwssN53wCblRpde3kB8UFSzZaMDUIzqsXzd8vFetRAIXuzE1pNpCsu2vNx
            a66pnFUweTLwCrpuFQlZ59cdqP0ZtIEE+cqQiUa3Ew/Ay9Q9RQjnQIz+k9txzCcH
            cVI1TMVX8uFgeU1pdB04mZgeF37IrDhWlK9+nB5iIYqqsZub3tJme6wpiSEn9syy
            9l0RpDl9WxBZb4zyPELYQkFG0zpZk9jPIjoI8OeGCRgPDcR20jA3lQPyGa69di6m
            gNcQYFq0S/aCKTVHswKBEDV8F51tcReAtuq/P+kpCC5DZBKM0vjS2KwxJKQqOlLl
            p8guEmKCr5/MCn6cTjShHCS5UvO9LygNM+XA2g13lQ6BGzuB7QmjNGca9qrajpTS
            XAESxTa+Mfmc4A7JEsE4jddqNvZjtCf9bkJ0QWlGRHwgOR9WQUPs4dt2kEaq6OiH
            mcyaJZdKt69EDCdonCScsqSWgnJDzGdIcrjm4SBGyED0he2p8ewmIofuvgTY
            =s7xe
            -----END PGP MESSAGE-----
          fp: 35A78E8DFBC452EBB4CC2DA011789BC5D5418D07
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
