---
- name: Update max_user_watches
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "65536"
    state: present
    sysctl_file: /etc/sysctl.d/98-kubernetes-fs.conf

- name: Disable swap at runtime
  ansible.builtin.service:
    name: dev-sdf3.swap
    state: stopped
  when: ansible_swaptotal_mb > 0

- name: Disable swap on boot
  ansible.builtin.command: systemctl mask dev-sdf3.swap
