# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-creds
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:9K+mXAb5AVV4Wr1/Gl3gYyDTOcxnsU8xMNYnzwQ=,iv:ATeStCpFhQqSrrXrMXWJ5oJ/sLTqxjs3XOg7B7RUoiE=,tag:pYcuQ+bTm/lrW9WRWjW78Q==,type:str]
    api-key: ENC[AES256_GCM,data:4gX58oSG9S5cikA10TWuDfPcdBok9TzIdLJQuKJ5BhdTsm8S2w==,iv:mQitQDtIc8DiOUzTkOhp5GYSbqMHnY1J5cfFwYQ1+20=,tag:U5nCUenN2XahdaPOg7EMIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-24T09:04:57Z"
    mac: ENC[AES256_GCM,data:1VXbJXNbXHOPlOa3cC5f1o+UOyvXxhmpkBsb5IMjCHsgRkj2/rJyjo28Dbc+2PKBTnKNsH7+Huty9xW5ISMFfVKjUGOl+U3dwOMP4ze5TBzPwMERUEIbusga7odtzWb38ZhnSvc4kaif/yj0gZ/l1Wl2plXxMLeSTFg2IZlS/00=,iv:RSsEKBrqO0OWGMtmLh/WWYu3vLbMwP3n9ePRe+oM07g=,tag:GuDRWQFKKrvdtlOwQCA8YQ==,type:str]
    pgp:
        - created_at: "2021-09-24T09:04:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+Rt2onsqezRARAAtJr8m+TL9Iy+O+osYZI/fX+GJvbTElcnC3DXC3LGyjFF
            OQFELgAz9RKCLoNUWObaGRQsOVhSXSuG2rxTYj17bL/eQH3aro310Z1n6GcHxxFv
            fcX5fgrRhFU5/KcqOAJy9oGXVLqg2avqITRj8frRw2n42PtlC8s3Z2c5Jlmi5DD6
            +ibM23Lfwwhc6Yom7yG875KpRZggkoxX1pTg1vaSJvjEmiWUuYN3mau6MzUobJzF
            la56p40WCvzAeFZBZPnKnaWaqi7RYuEBm9gdcyPXqcdXXF5lgEqG1S7J/EHqJ8dT
            ZIwBARtyAe97iMAPV9MFG1iM8zsCjVHFgYlnsPE7dMGhc5azjw1Orb1t/bdAUL8T
            Rss8V5ohZNKs5tSCpjYIxwNzc/BnNuQnBnEyVVRnHaSK9DBW1196WqkIuQDr2Fo+
            0Mc+Jx/cuPx+GT1y4v+vuc4kS5wi7PsnqWvaHAXw1HrG/CUHG77urLzucpNyHmjo
            4+qVebu8TuhjGXpvHFw4Ka2Sz4or/uQPfDR0JWRFZQ3SUnOh0ftaV/lXGUp6Va85
            0clQfyqroVsHLRDLLbAzXLhotCJBPIzOxa6XKHoWwLdNur2bALt9c10tQnawA+Li
            cZA6bQQ9L1mpaKoGSdVO4opNakdctmNmkDtuz0oAOw4fkvJFxB8iR+0+PXVOKnXS
            XgGP8G5KSUcmC+piX1sM4UWU/Oz1GVt9nwfNmNUzxrZKotwQfcIXwm9MOYvLRzxV
            YiETF15YraGpYGHN1haAmv+97GDPAc/smunblb+GC1TjgiJWZPf5RUiYr4qiId4=
            =FNOQ
            -----END PGP MESSAGE-----
          fp: EE28A8EBC835173892520CC88C929A715870568E
        - created_at: "2021-09-24T09:04:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6HOrcCh3eSZARAAjnDUJx6qsZlF8oMPABCgVALVQki5CF+btpwcLZtPlyVy
            sj6Kvung79vXZ8dRZZpj3tnMPISrjy6VoSGjmi3+yIuKSxMx/7r0WbfClEwWd6H7
            V0ZEMTWEeiYAK59/SY6XYHyUtSSzEbd7aBUAxsr3tJnh5+259Et53YPjZQUsxZin
            uTCU/YKDQ43KOfhLlE8PCdBD1UXcv9iP5jTXpSCsKBxaLVI2+bsHEocNcASQWbkg
            UL1fu1WVc4u+WH6dI1fFzZOKoTyisFvhxALhoASR4pLExTi+4pWPIvRoLv/bF9Wt
            G5qgD/g7Gp0Y5Pq8UKlfW40Ud9J71cNrTVe9mMJLPQ2HgpJkY9N3bUTDhhpEyFvD
            IvLm8+hsH+N5zpiXG8YJGM5HNUF0dZN7KfarEMjJK4/WdWL4Lw3T0tQ9eYWb7tEL
            IlzyMPTp/2vCOT/XqEtbVx+jNwnjdYMIsaTFZLp7pC1sKjhvRfKSBcb0yYsPtUGm
            XmhymKdfne97gEEIPlWLnlB9v0eOdQ9fkyBKNkxMTfoDS9VMv1T534wEpaQokWzg
            X/eEwSuCbnO+qPia6dOagEKP4T0r4EvRATOw20MhkH2ZNHE3LXMMd+LKpVRjeanV
            dyTkftkdb/BNlBV9DkkEwur0x7tYhsHVHDcBO9lPDsaCufF/AhIK3zVNPJ2dG+rS
            XgHZArB4/scyJ8C0Gd1HJ2lxbYYChQDla5Aw03ULpo9C05qWLSd//gI+Yj1xnnTo
            nefR2a3t8KQoHmVMSTNouzzSvkE/E2oK+H7Sbey1uOIFgdW+CSx4cubIjUTZ6Ek=
            =j5w+
            -----END PGP MESSAGE-----
          fp: 35A78E8DFBC452EBB4CC2DA011789BC5D5418D07
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
