# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:7UySAs8fuWAeERpOMQa2uJAWLRlARtx82dcLzTImdc6uk++UuLJsaQ==,iv:iJTQMDdLJzhWpAhr8PkNpmVz8VjbZFjLncRvDjz3vJY=,tag:tDc+8nb1oFDFW5dIlb9s1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-24T05:35:34Z"
    mac: ENC[AES256_GCM,data:p4ifnDaUAFmOggwm4LFRENb05XfwdZNgHyvrheEYfGyh1ZE9aWIUt27x4xbNFzLBf6nXBQOA6BbExaCc/6FBoYhNIvh90KTo6B3+dNaVNS8QqJZfBH5UZMIg+CZsczQAcLT+4uDYND52hH4mDlkgckeJEmDLB3Yk6EhukuQ1sS4=,iv:EJdoYvNTpTr8NcYiR9tgTRAUBWTIe04kIykU1PZgOBI=,tag:AQbVKxYLYSHmnVgx37M7Ow==,type:str]
    pgp:
        - created_at: "2021-09-24T05:35:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+Rt2onsqezRAQ//WQbUHKFM/qxTXUzoSWA+Zin1T5/FCfYdPoJCKCxA3Qg2
            aVx9YlgEExKKiklYX3SJdV/mQGsN/Pv//2CjWGNoF9qLSoIk1uy1WetQSTgK1bd7
            S9qbIGSkgvho/eLtdPqZ/JabHMZ6wYwKJAUJBpWh0x0sd1rVwebJLIU/EDyuqGch
            kVCDYcPttDWskH0gCaCqJM7AVHyau30nLmsRzzZ43549x3VJ5Mqd6XhO3/BKoMoK
            auxv77HXz18oeceOdHkG5hNkZtb57sEQiiJ8djzD+NTUNNdw68KhtBH5PZlpiRiL
            x2Bf5FDtXk1CPAUtv5hfZs8mejmKULQ+6TN3i3n7FD/8dnYf03+/ItX7rFENaWYj
            JPfEl3f6fl0WCc2s6luZBgthhQjIHfk/P886IXsCiuRYcj8btQgfU5m0bs3Fk5Bv
            3jnlc+nat1H916AehKib2fzR7dSuGufKKhlBAAsZGyu58yUD3dzbKhrDJww2WJi1
            tbOZs8iIua3fX9ObL8BiwBFkqak8G2a97CdzwQGdGvg3Z6ciVgwCJhGdUDvcIu2a
            63/1yjXQz/fdoFSgu3Fhwvf4boJcBhJDnrRXmOZV5q3Bro+dopOt9mmeh1XhgqLP
            hEiNPC21m0/6gmlduPL/7xat+oebjOuVjYd5TGHriSyrTiMspiiu7LoNFvin6qnS
            XgGU8umoJPMPLL2NuG41wbljMIS8LjnoX/SVzze/lEZqujticidGT7kHKlwCtQUc
            6bF2soYEkku6tx2WzdLLWfljs6ryLYNf6JPnGiMqz6DuYEKB9ApeVVt165Gn8TA=
            =O6bQ
            -----END PGP MESSAGE-----
          fp: EE28A8EBC835173892520CC88C929A715870568E
        - created_at: "2021-09-24T05:35:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6HOrcCh3eSZARAAlNdEq2QojX+ZEl0v5tNay0LKYARzNYL9pTJNtSBFfvPx
            9l8FFRE97jskN6Yi/lqtp3595uPMSzhcPbtfDZOkF8iiP0RVfJlC+PsOlBVkMXS4
            g/2fncscLl+OUvmQ7kBwDEzbmLYfUI1N5ZyPKro8NZoUJG4OQDLQ7Fmabp7Pjdp9
            YFNenjpKD/xIvTWi4C5Op8kHuoIvJW/LZD+hrx0Fy/xhVEakL6g5qR3Vs92Am/yg
            UGTYp7HMXlsCWRalOQm06/EIN7gAZ6Bj24kzre49SiBqE+NGHiGrZWYYqzU3Ifjz
            jWhx8HtoQIp2nrXPjTjA2+f+e/N0GeInsPc/WhB4s7mL+5F9SEOlD9lULmAyzhCD
            /aRzDWdQWT4FvoHR4cfYwhawc/vXc30lVmLQ3XUjkFHABbfCpQDEtLXKusOPFjPq
            f6/4R/CLcX3BSEApOnEZWG3KFRPCLumY3HkBR+NY0rYaxoFnFKQITngCYX+5wmwA
            1KKfgf3wL6SrNm46vM/QV59VcgMm0QdNjFfsxKBlZ65ffpZtu9Mc7yiHp2dloOWA
            OEOpaugndulh9dvSVaCI7HtWiJkWBKJ4Vsxl5r1Czakhp7EGjq3qVmwqj34LbJM1
            Y+iaUMpCkiJvztq8Z5CoyOtULZNFc7w4uwUQi6PRFMhoH9bKEZIGjeav32xcmw/S
            XgGD27fdnyj6RqpJodkq2bZEmmRHSJcGNIEygWAW5kY7yBID15AC3vzlM38CI2/B
            /+BbfhYhuLOm+EBKRlDpkn7LQMg1tWzmOAvadK7UI3VV8nSPX8OX2Sd3L4fsHtE=
            =CPXx
            -----END PGP MESSAGE-----
          fp: 35A78E8DFBC452EBB4CC2DA011789BC5D5418D07
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
